matrix:
  include:
    - name: "report - arara"
      sudo: required
      language: generic
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y --no-install-recommends texlive-full
      install:
        - cd ./report
        - arara --log --verbose report.tex
      script:
        - cd ./report
        - chktex report.tex
