dist: xenial
matrix:
  include:
    - name: "report - arara"
      sudo: required
      language: generic
      addons:
        apt:
          packages:
            - texlive-full
      install:
        - cd ./report
        - arara --log --verbose report.tex
      script:
        - cd ./report
        - chktex report.tex
