dist: xenial
matrix:
  include:
    - name: "report - arara"
      sudo: required
      language: generic
      addons:
        apt:
          sources:
            - sourceline: "deb http://miktex.org/download/ubuntu xenial universe"
          packages:
            - miktex
      before_install:
        - sudo miktexsetup --shared=yes finish
        - sudo initexmf --admin --set-config-value [MPM]AutoInstall=1
      install:
        - cd ./report
        - arara --log --verbose report.tex
      script:
        - cd ./report
        - chktex report.tex
