/* Generated by AN DISI Unibo */ 
package it.unibo.onecellforward;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Onecellforward extends QActorMsgQueue{
	public MsgHandle_Onecellforward(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
