/* Generated by AN DISI Unibo */ 
package it.unibo.world_observer;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractWorld_observer extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	//protected String mqttServer = "tcp://127.0.0.1:1883";
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractWorld_observer(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/world_observer/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/world_observer/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("doObserve",doObserve);
	    	stateTab.put("evaluateTemperature",evaluateTemperature);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "world_observer tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	//ConnectToSubscribe
	    	connectAndSubscribe( this.getName(), "tcp://127.0.0.1:1883", "unibo/environment");
	    	//switchTo doObserve
	        switchToPlanAsNextState(pr, myselfName, "world_observer_"+myselfName, 
	              "doObserve",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun doObserve = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_doObserve",0);
	     pr.incNumIter(); 	
	    	String myselfName = "doObserve";  
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?evaluateEnvironment" )) != null ){
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "environment(X)","environment(ok)", guardVars ).toString();
	    	emit( "environment", temporaryStr );
	    	}
	    	else{ temporaryStr = QActorUtils.unifyMsgContent(pengine, "environment(X)","environment(notok)", guardVars ).toString();
	    	emit( "environment", temporaryStr );
	    	}
	    	//bbb
	     msgTransition( pr,myselfName,"world_observer_"+myselfName,false,
	          new StateFun[]{stateTab.get("evaluateTemperature") }, 
	          new String[]{"true","E","temperature" },
	          1000, "doObserve" );//msgTransition
	    }catch(Exception e_doObserve){  
	    	 println( getName() + " plan=doObserve WARNING:" + e_doObserve.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//doObserve
	    
	    StateFun evaluateTemperature = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("evaluateTemperature",-1);
	    	String myselfName = "evaluateTemperature";  
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("temperature(X)");
	    	if( currentEvent != null && currentEvent.getEventId().equals("temperature") && 
	    		pengine.unify(curT, Term.createTerm("temperature(X)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			/* replaceRule */
	    			String parg1="temperature(_)"; 
	    			String parg2="temperature(X)"; 
	    			parg1 = updateVars( Term.createTerm("temperature(X)"),  Term.createTerm("temperature(X)"), 
	    				    		  			Term.createTerm(currentEvent.getMsg()), parg1);
	    			parg2 = updateVars( Term.createTerm("temperature(X)"),  Term.createTerm("temperature(X)"), 
	    				    		  			Term.createTerm(currentEvent.getMsg()), parg2);
	    			replaceRule(parg1,parg2);
	    	}
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("temperature(X)");
	    	if( currentEvent != null && currentEvent.getEventId().equals("temperature") && 
	    		pengine.unify(curT, Term.createTerm("temperature(X)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg="state(temperature,X)";
	    			/* SendDispatch */
	    			parg = updateVars(Term.createTerm("temperature(X)"),  Term.createTerm("temperature(X)"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) sendMsg("stateUpdate","console", QActorContext.dispatch, parg ); 
	    	}
	    	//switchTo doObserve
	        switchToPlanAsNextState(pr, myselfName, "world_observer_"+myselfName, 
	              "doObserve",false, false, null); 
	    }catch(Exception e_evaluateTemperature){  
	    	 println( getName() + " plan=evaluateTemperature WARNING:" + e_evaluateTemperature.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//evaluateTemperature
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
