/* Generated by AN DISI Unibo */ 
package it.unibo.world_observer;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_World_observer extends QActorMsgQueue{
	public MsgHandle_World_observer(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
