/* Generated by AN DISI Unibo */ 
package it.unibo.robot_discovery_mind;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Robot_discovery_mind extends QActorMsgQueue{
	public MsgHandle_Robot_discovery_mind(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
